displayName: Cors Preflight
type: middleware
iconPath: .assets/icon.jpg

import: github.com/Medzoner/traefik-plugin-cors-preflight

summary: 'Pass the browser cors preflight with response status 204 for Method OPTIONS'

testData:
  Code: 204
  Method: 'OPTIONS'
  Debug: true
